# Generated by Django 5.1.7 on 2025-04-11 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoopjoy', '0004_rename_address_line_address_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoriteflavor',
            old_name='name',
            new_name='flavor_name',
        ),
        migrations.AlterField(
            model_name='favoriteflavor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_flavors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
