# Generated by Django 5.1.6 on 2025-05-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoopjoy', '0007_remove_order_order_details_order_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('sticks', 'Sticks'), ('cones', 'Cones'), ('tubs', 'Tubs')], default='sticks', max_length=20),
        ),
    ]
