# Generated by Django 5.1.6 on 2025-05-26 05:10

from django.db import migrations

def add_products(apps, schema_editor):
    Product = apps.get_model('scoopjoy', 'Product')
    products = [
        {'name': "Frosty Swirl", 'price': 350, 'image': "frosty_swirl_cone.jpeg", 'category': 'cones', 'discounted_price': None},
        {'name': "Waffle Crunch", 'price': 370, 'image': "waffle_crunch_cone.jpeg", 'category': 'cones', 'discounted_price': None},
        {'name': "Twirl 'n' Twist", 'price': 330, 'image': "Twirl_n_twist_cone.jpeg", 'category': 'cones', 'discounted_price': None},
        {'name': "Sprinkle Spike", 'price': 320, 'image': "sprinkle_spike_cone.jpeg", 'category': 'cones', 'discounted_price': None},
        {'name': "Crisp Cascade", 'price': 350, 'image': "crisp_cascade_cone.jpeg", 'category': 'cones', 'discounted_price': None},
        {'name': "Toasty Delight", 'price': 360, 'image': "tosaty_delight_cones.jpeg", 'category': 'cones', 'discounted_price': None},
        {'name': "Choco Cone Clash", 'price': 380, 'image': "mocha_matness_cones.jpeg", 'category': 'cones', 'discounted_price': None},
        {'name': "Berry Bliss", 'price': 350, 'image': "berry_bliss_cones.jpeg", 'category': 'cones', 'discounted_price': None},
        {'name': "Caramel Crisp", 'price': 360, 'image': "caramel_crisp_cones.jpeg", 'category': 'cones', 'discounted_price': None},
        {'name': "Mocha Madness", 'price': 390, 'image': "mocha_matness_cones_2.jpeg", 'category': 'cones', 'discounted_price': None},
        {'name': "Peanut Pop", 'price': 360, 'image': "peanut_pop_cones.jpeg", 'category': 'cones', 'discounted_price': None},
        {'name': "Choco Crunch Stick", 'price': 60, 'image': "coffee_crunch_stick.jpeg", 'category': 'sticks', 'discounted_price': None},
        {'name': "Vanilla Dream Stick", 'price': 50, 'image': "vanilla_dream_stick.jpeg", 'category': 'sticks', 'discounted_price': None},
        {'name': "Strawberry Blast Stick", 'price': 55, 'image': "straberry_blast_stick.jpeg", 'category': 'sticks', 'discounted_price': None},
        {'name': "Almond Delight Stick", 'price': 65, 'image': "almond_delight_stick.jpeg", 'category': 'sticks', 'discounted_price': None},
        {'name': "Butterscotch Stick", 'price': 60, 'image': "butterscoch__stick.jpeg", 'category': 'sticks', 'discounted_price': None},
        {'name': "Mango Magic Stick", 'price': 50, 'image': "mango_magic_stick.jpeg", 'category': 'sticks', 'discounted_price': None},
        {'name': "Pistachio Pleasure Stick", 'price': 90, 'image': "pistachio_pleasure_stick.jpeg", 'category': 'sticks', 'discounted_price': None},
        {'name': "Caramel Swirl Stick", 'price': 60, 'image': "caramel_swirl_stick.jpeg", 'category': 'sticks', 'discounted_price': None},
        {'name': "Coffee Crunch Stick", 'price': 60, 'image': "coffee_crunch_stick.jpeg", 'category': 'sticks', 'discounted_price': None},
        {'name': "Mint Choco Stick", 'price': 40, 'image': "mint_choco_stick.jpeg", 'category': 'sticks', 'discounted_price': None},
        {'name': "Fruity Fusion Stick", 'price': 70, 'image': "fruite_fussion.jpeg", 'category': 'sticks', 'discounted_price': None},
        {'name': "Blueberry Chill Stick", 'price': 80, 'image': "blueberry_chill.jpeg", 'category': 'sticks', 'discounted_price': None},
        {'name': "Cookies & Cream Stick", 'price': 70, 'image': "cookies__cream.jpeg", 'category': 'sticks', 'discounted_price': None},
        {'name': "Orange Zest Stick", 'price': 30, 'image': "orange_zest_ice.jpeg", 'category': 'sticks', 'discounted_price': None},
        {'name': "Hazelnut Stick", 'price': 100, 'image': "hazelnut_heaven.jpeg", 'category': 'sticks', 'discounted_price': None},
        {'name': "Churned Bliss", 'price': 650, 'image': "churned_bliss__tubs.jpeg", 'category': 'tubs', 'discounted_price': None},
        {'name': "Dreamy Scoop", 'price': 620, 'image': "dreamy_scoop.jpeg", 'category': 'tubs', 'discounted_price': None},
        {'name': "Velvet Chill", 'price': 680, 'image': "velvet_chill.jpeg", 'category': 'tubs', 'discounted_price': None},
        {'name': "Midnight Indulgence", 'price': 720, 'image': "midnight_indegence.jpeg", 'category': 'tubs', 'discounted_price': None},
        {'name': "Berry Bonanza", 'price': 660, 'image': "berry_bonanza.jpeg", 'category': 'tubs', 'discounted_price': None},
        {'name': "Tropical Frost", 'price': 670, 'image': "tropical_frost.jpeg", 'category': 'tubs', 'discounted_price': None},
        {'name': "Chocolate Abyss", 'price': 680, 'image': "chocolate_abyss_icecream.jpeg", 'category': 'tubs', 'discounted_price': None},
        {'name': "Strawberry Serenade", 'price': 660, 'image': "stroberry_nadesere.jpeg", 'category': 'tubs', 'discounted_price': None},
        {'name': "Cookie Dough Delight", 'price': 690, 'image': "cookie_dough_delight.jpeg", 'category': 'tubs', 'discounted_price': None},
        {'name': "Pistachio Paradise", 'price': 600, 'image': "pistachio_paradisc.jpeg", 'category': 'tubs', 'discounted_price': None},
    ]
    for product in products:
        Product.objects.create(**product)

def remove_products(apps, schema_editor):
    Product = apps.get_model('scoopjoy', 'Product')
    Product.objects.all().delete()

class Migration(migrations.Migration):
    dependencies = [
        ('scoopjoy', '0008_product_category'),  # Updated to the correct previous migration
    ]

    operations = [
        migrations.RunPython(add_products, remove_products),
    ]